name: Build Clap API
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Build docker image
        run: docker build -t feeeeliipe/clap-api:${{ github.sha }} .
      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: feeeeliipe
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_SECRET }}
      - name: Push image to Registry
        run: docker push feeeeliipe/clap-api:${{ github.sha }}