name: Build Clap API
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Build docker image
        run: docker build -t feeeeliipe/clap-api:${{ github.sha }} .
      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: feeeeliipe
          password: ${{ secrets.DOCKER_HUB_SECRET }}
      - name: Push image to Registry
        run: docker push feeeeliipe/clap-api:${{ github.sha }}
  deployment:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
      - name: Update deployment manifest
        run: |
          cd k8s/
          kustomize edit set image feeeeliipe/clap-api:${{ github.sha }}
          git add .
          git commit -m "Updating k8s manifest with new version: `${{ github.sha }}`"
          git push
    
