name: Build Clap API
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Build docker image
        run: docker build -t feeeeliipe/clap-api:${{ github.sha }} .
      - name: Login to docker hub
        uses: docker/login-action@v2
        with:
          username: feeeeliipe
          password: ${{ secrets.DOCKER_HUB_SECRET }}
      - name: Push image to Registry
        run: docker push feeeeliipe/clap-api:${{ github.sha }}
  update-infra:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Update infra repository
        uses: feeeeliipe/clap-api-infra-k8s/.github/workflows/update-app-image.yaml@main
        with:
          newImage: feeeeliipe/clap-api:${{ github.sha }}
